# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b884505ca5c90ee63a8562d879cee7f4119276ceec5022fd571ff0b0a16911e2772c79918eff847b55a5fd88dba3231ecf9df75f891a40d3cca8e5ba117460de

test:
  secret_key_base: 93f28abc041b2ca80557866aa17bddbd7ad152c6c530d5754cd8b6348f14ab4676e605c3181df84ee6cbe82f46e30023d21b116d04d4d9d907dc7dd23746914f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
